spring:
  application:
    name: jwt-authentication

  datasource:
    url: jdbc:h2:file:./data/database
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    com.evasquare.jwt_authentication: DEBUG
    org.springframework.security: DEBUG
