spring:
  application:
    name: jwt-authentication
  config:
    import: classpath:application-secret.yml

  datasource:
    url: jdbc:h2:file:./data/database
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${jwt.secret}
  expiration: 86400000
  refresh-expiration: 604800000
  admin-password: ${jwt.admin-password}

logging:
  level:
    com.evasquare.jwt_authentication: DEBUG
    org.springframework.security: DEBUG
